spring:
  application:
    name: voting-api

  datasource:
    url: jdbc:postgresql://localhost:5432/voting_api
    username: voting_user
    password: voting_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

external:
  cpf-eligibility:
    base-url: https://run.mocky.io/v3/57f23672-c15f-48f8-90d3-d84ce00250b8/
