CREATE TABLE pautas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    criada_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pauta_id BIGINT NOT NULL,
    aberta_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    encerra_em TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_sessoes_pauta
        FOREIGN KEY (pauta_id)
        REFERENCES pautas (id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_sessoes_pauta
        UNIQUE (pauta_id),

    CONSTRAINT ck_sessoes_periodo
        CHECK (encerra_em > aberta_em)
);

CREATE TABLE votos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id BIGINT NOT NULL,
    associado_id VARCHAR(255) NOT NULL,
    opcao VARCHAR(3) NOT NULL,
    votado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_votos_sessao
        FOREIGN KEY (sessao_id)
        REFERENCES sessoes (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_votos_opcao
        CHECK (opcao IN ('SIM', 'NAO')),

    CONSTRAINT uq_votos_sessao_associado
        UNIQUE (sessao_id, associado_id)
);

CREATE INDEX idx_votos_sessao_id
    ON votos (sessao_id);